# authors:        Cathal Dwyer, Giuseppe Esposito;
# stN:            22391376, 22702205;

# ====== GENERAL ======================
# time + seed
tick_ms=100
ticks_per_day=1000
random_seed=42


# ====== RESOURCES =====================
# section
section_names=electronics,books,medicines,clothes,tools
initial_boxes_per_section=5
section_capacity=10

# trolleys (min value = 2)
num_trolleys=5


# ====== CONURRENT ACTORS ==============
# delivery 
delivery_probability=0.01
boxes_per_delivery=10

# stockers num + movment and job timing
num_stockers=5
travel_base_ticks=10
travel_ticks_per_box=1
stock_ticks_per_box=1
staging_take_ticks=1

# stockers breaks
stocker_break_interval_min=200
stocker_break_interval_max=300
stocker_break_duration=150

# pickers
num_pickers=2
target_picks_per_day=100
pick_ticks=1

